create extension if not exists pgcrypto;

create table if not exists documents (
    id uuid primary key default gen_random_uuid(),
    filename text not null,
    original_name text,
    doc_type text not null,
    dataset_key text,
    data_kind text,
    state text,
    survey_year text,
    agency_type text,
    survey_scope text,
    status text not null,
    row_count integer not null default 0,
    keywords jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

alter table documents add column if not exists original_name text;
alter table documents add column if not exists doc_type text;
alter table documents add column if not exists dataset_key text;
alter table documents add column if not exists data_kind text;
alter table documents add column if not exists state text;
alter table documents add column if not exists survey_year text;
alter table documents add column if not exists agency_type text;
alter table documents add column if not exists survey_scope text;
alter table documents add column if not exists status text;
alter table documents add column if not exists row_count integer not null default 0;
alter table documents add column if not exists keywords jsonb not null default '[]'::jsonb;
alter table documents add column if not exists created_at timestamptz not null default timezone('utc', now());

create table if not exists deleted_docs (
    id uuid primary key,
    filename text not null,
    original_name text,
    doc_type text not null,
    dataset_key text,
    data_kind text,
    state text,
    survey_year text,
    agency_type text,
    survey_scope text,
    status text not null,
    row_count integer not null default 0,
    keywords jsonb not null default '[]'::jsonb,
    created_at timestamptz not null,
    deleted_at timestamptz not null default timezone('utc', now())
);

alter table deleted_docs add column if not exists original_name text;
alter table deleted_docs add column if not exists doc_type text;
alter table deleted_docs add column if not exists dataset_key text;
alter table deleted_docs add column if not exists data_kind text;
alter table deleted_docs add column if not exists state text;
alter table deleted_docs add column if not exists survey_year text;
alter table deleted_docs add column if not exists agency_type text;
alter table deleted_docs add column if not exists survey_scope text;
alter table deleted_docs add column if not exists status text;
alter table deleted_docs add column if not exists row_count integer not null default 0;
alter table deleted_docs add column if not exists keywords jsonb not null default '[]'::jsonb;
alter table deleted_docs add column if not exists created_at timestamptz;
alter table deleted_docs add column if not exists deleted_at timestamptz not null default timezone('utc', now());

create table if not exists uploaded_dataset_rows (
    id bigint generated by default as identity primary key,
    document_id uuid not null references documents(id) on delete cascade,
    dataset_key text,
    data_kind text,
    state text,
    survey_year text,
    agency_type text,
    survey_scope text,
    sheet_name text,
    sheet_role text,
    row_index integer not null,
    row_data jsonb not null,
    created_at timestamptz not null default timezone('utc', now())
);

alter table uploaded_dataset_rows add column if not exists dataset_key text;
alter table uploaded_dataset_rows add column if not exists data_kind text;
alter table uploaded_dataset_rows add column if not exists state text;
alter table uploaded_dataset_rows add column if not exists survey_year text;
alter table uploaded_dataset_rows add column if not exists agency_type text;
alter table uploaded_dataset_rows add column if not exists survey_scope text;
alter table uploaded_dataset_rows add column if not exists sheet_name text;
alter table uploaded_dataset_rows add column if not exists sheet_role text;
alter table uploaded_dataset_rows add column if not exists row_index integer;
alter table uploaded_dataset_rows add column if not exists row_data jsonb;
alter table uploaded_dataset_rows add column if not exists created_at timestamptz not null default timezone('utc', now());

create index if not exists idx_documents_doc_type_created_at
    on documents (doc_type, created_at desc);

create index if not exists idx_documents_dataset_key_created_at
    on documents (dataset_key, created_at desc);

create index if not exists idx_documents_survey_year_state
    on documents (survey_year, state, created_at desc);

create index if not exists idx_uploaded_dataset_rows_document_id
    on uploaded_dataset_rows (document_id, row_index);

create index if not exists idx_uploaded_dataset_rows_sheet_role
    on uploaded_dataset_rows (document_id, sheet_role, row_index);

create table if not exists survey_update_submissions (
    id uuid primary key default gen_random_uuid(),
    topic_key text not null,
    topic_label text not null,
    state text not null,
    survey_year text not null,
    respondent_name text,
    status text not null default 'submitted',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table survey_update_submissions add column if not exists topic_key text;
alter table survey_update_submissions add column if not exists topic_label text;
alter table survey_update_submissions add column if not exists state text;
alter table survey_update_submissions add column if not exists survey_year text;
alter table survey_update_submissions add column if not exists respondent_name text;
alter table survey_update_submissions add column if not exists status text not null default 'submitted';
alter table survey_update_submissions add column if not exists created_at timestamptz not null default timezone('utc', now());
alter table survey_update_submissions add column if not exists updated_at timestamptz not null default timezone('utc', now());

create table if not exists survey_update_answers (
    id bigint generated by default as identity primary key,
    submission_id uuid not null references survey_update_submissions(id) on delete cascade,
    question_id text not null,
    answer_text text,
    answer_number numeric,
    answer_json jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

alter table survey_update_answers add column if not exists submission_id uuid;
alter table survey_update_answers add column if not exists question_id text;
alter table survey_update_answers add column if not exists answer_text text;
alter table survey_update_answers add column if not exists answer_number numeric;
alter table survey_update_answers add column if not exists answer_json jsonb;
alter table survey_update_answers add column if not exists created_at timestamptz not null default timezone('utc', now());

create index if not exists idx_survey_update_submissions_lookup
    on survey_update_submissions (topic_key, state, survey_year, updated_at desc);

create index if not exists idx_survey_update_answers_submission
    on survey_update_answers (submission_id, question_id);

create table if not exists expert_review_sessions (
    id uuid primary key default gen_random_uuid(),
    reviewer_name text,
    review_year text not null,
    state text not null,
    domain_key text not null,
    domain_label text not null,
    dataset_version text,
    status text not null default 'draft',
    overall_comment text,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    submitted_at timestamptz
);

alter table expert_review_sessions add column if not exists reviewer_name text;
alter table expert_review_sessions add column if not exists review_year text;
alter table expert_review_sessions add column if not exists state text;
alter table expert_review_sessions add column if not exists domain_key text;
alter table expert_review_sessions add column if not exists domain_label text;
alter table expert_review_sessions add column if not exists dataset_version text;
alter table expert_review_sessions add column if not exists status text not null default 'draft';
alter table expert_review_sessions add column if not exists overall_comment text;
alter table expert_review_sessions add column if not exists created_at timestamptz not null default timezone('utc', now());
alter table expert_review_sessions add column if not exists updated_at timestamptz not null default timezone('utc', now());
alter table expert_review_sessions add column if not exists submitted_at timestamptz;

create table if not exists expert_review_items (
    id bigint generated by default as identity primary key,
    session_id uuid not null references expert_review_sessions(id) on delete cascade,
    subaspect_key text not null,
    subaspect_label text not null,
    current_value text,
    source_basis text,
    expert_judgment text,
    suggested_value text,
    confidence_level text,
    comment text,
    recommend_method_change boolean not null default false,
    created_at timestamptz not null default timezone('utc', now())
);

alter table expert_review_items add column if not exists session_id uuid;
alter table expert_review_items add column if not exists subaspect_key text;
alter table expert_review_items add column if not exists subaspect_label text;
alter table expert_review_items add column if not exists current_value text;
alter table expert_review_items add column if not exists source_basis text;
alter table expert_review_items add column if not exists expert_judgment text;
alter table expert_review_items add column if not exists suggested_value text;
alter table expert_review_items add column if not exists confidence_level text;
alter table expert_review_items add column if not exists comment text;
alter table expert_review_items add column if not exists recommend_method_change boolean not null default false;
alter table expert_review_items add column if not exists created_at timestamptz not null default timezone('utc', now());

create index if not exists idx_expert_review_sessions_lookup
    on expert_review_sessions (review_year, state, domain_key, updated_at desc);

create index if not exists idx_expert_review_items_session
    on expert_review_items (session_id, subaspect_key);

alter table documents disable row level security;
alter table deleted_docs disable row level security;
alter table uploaded_dataset_rows disable row level security;
alter table survey_update_submissions disable row level security;
alter table survey_update_answers disable row level security;
alter table expert_review_sessions disable row level security;
alter table expert_review_items disable row level security;
